#!/bin/sh
#####
# Peter Leimbach
# 30.03.2021
# Aufgabe: einfache, automatisierte Installation von Arch Linux auf meinen Rechnern
#####

# Variablen setzen
# Test
# Das ist meine SSD in dem kleinen Intel NUC
PARTITION=/dev/nvme0n1
export PARTITION
# der Hostname sollte gesetzt werden, ist aber beliebig
HOSTNAME=archfun

# deutsche Tastaturbelegung laden
loadkeys de-latin1

# Festplatte partitionieren
# es werden alle alten Partitionen gelöscht
sgdisk --zap-all ${PARTITION}
# es werden die üblichen drei Partitionen angelegt
sgdisk -n 0:0:+1GiB -t 0:ef00 -c 0:EFIBOOT ${PARTITION}
sgdisk -n 0:0:+8GiB -t 0:8200 -c 0:p_swap ${PARTITION}
sgdisk -n 0:0:0 -t 0:8300 -c 0:p_arch ${PARTITION}

# Partitionen formatieren
mkfs.fat -F 32 -n EFIBOOT ${PARTITION}p1
mkswap -L p_swap ${PARTITION}p2
mkfs.ext4 -L p_arch ${PARTITION}p3

# Paritionen mounten
mount -L p_arch /mnt
mkdir -p /mnt/boot
mount -L EFIBOOT /mnt/boot
swapon -L p_swap

# Basissystem installieren
pacstrap /mnt base base-devel linux linux-firmware dhcpcd nano intel-ucode git vim bash

# Filesystem Tabelle erzeugen
genfstab -U -p /mnt >> /mnt/etc/fstab
sed "s/relatime/defaults,noatime/" /mnt/etc/fstab  > /mnt/etc/ttt
mv /mnt/etc/ttt /mnt/etc/fstab

# chroot in neues Basissystem
cp /root/simplearchinstall/step2 /mnt/step2
arch-chroot /mnt/ /usr/bin/sh /step2
