#!/bin/sh

# Variablen setzen
PARTITION=/dev/nvme0n1
export PARTITION
HOSTNAME=archfun

# deutsche Tastaturbelegung laden
loadkeys de-latin1

# Festplatte partitionieren
# es werden alle alten Partitionen gelöscht
sgdisk --zap-all ${PARTITION}
# es werden die üblichen drei Partitionen angelegt
sgdisk -n 0:0:+1GiB -t 0:ea00 -c 0:EFIBOOT ${PARTITION}
sgdisk -n 0:0:+4GiB -t 0:8200 -c 0:p_swap ${PARTITION}
sgdisk -n 0:0:0 -t 0:8300 -c 0:p_arch ${PARTITION}

# Partitionen formatieren
mkfs.fat -F 32 -n EFIBOOT ${PARTITION}p1
mkswap -L p_swap ${PARTITION}p2
mkfs.ext4 -L p_arch ${PARTITION}p3

# Paritionen mounten
mount -L p_arch /mnt
mkdir /mnt/boot
mount -L EFIBOOT /mnt/boot
swapon -L p_swap

# Filesystem Tabelle erzeugen
genfstab -U -p /mnt >> /mnt/etc/fstab
vi /mnt/etc/fstab

# Basissystem installieren
pacstrap /mnt base base-devel linux linux-firmware dhcpcd nano intel-ucode

# chroot in neues Basissystem
arch-chroot /mnt/

# Hostnamen setzen
echo archlinux > /etc/hostname

# Die Spracheinstellung (Locale) auf Deutsch festlegen.
echo LANG=de_DE.UTF-8 > /etc/locale.conf
locale-gen

echo KEYMAP=de-latin1 > /etc/vconsole.conf
echo FONT=lat9w-16 >> /etc/vconsole.conf

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

cat <<EOF > /etc/hosts
#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost ${HOSTNAME}
::1		localhost.localdomain	localhost
EOF

# Initramfs erzeugen
mkinitcpio -p linux

# Passwort für den root-User setzen
echo "Passwort für root setzen\n"
passwd

# Installation des Bootloaders
pacman -Syu
pacman -S efibootmgr dosfstools gptfdisk vim
efibootmgr -c -d /dev/sda -p 1 -l \vmlinuz-linux -L "Arch Linux efistub" -u "initrd=\initramfs-linux.img root=LABEL=p_arch rw"
efibootmgr -c -d /dev/sda -p 1 -l \vmlinuz-linux -L "Arch Linux fallback efistub" -u "initrd=\initramfs-linux-fallback.img root=LABEL=p_arch rw"

# weiteren Benutzer anlegen und den wichtigsten Gruppen zuweisen
pacman -S bash
useradd -m -g users,wheel -s /bin/bash peter
passwd peter
vi /etc/sudoers

systemctl enable --now fstrim.timer
pacman -S acpid dbus avahi cups
systemctl enable acpid
systemctl enable avahi-daemon
systemctl enable cups.service
systemctl enable --now systemd-timesyncd.service

pacman -S xorg-server xorg-xinit xf86-video-intel
cat <<EOF > /etc/X11/xorg.conf.d/00-keyboard.conf
Section "InputClass"
      Identifier "keyboard"
      MatchIsKeyboard "yes"
      Option "XkbLayout" "de"
      Option "XkbModel" "pc105"
      Option "XkbVariant" "deadgraveacute"
EndSection
EOF

pacman -S xf86-input-synaptics

# Xfce an sich
pacman -S xfce4 

# xfce4-goodies enthält weitere Programme und Plugins.
pacman -S xfce4-goodies

pacman -S lightdm lightdm-gtk-greeter
systemctl enable lightdm.service

# change root verlassen
exit

# Filesystem für die Installation unmounten
umount -R /mnt

#reboot
